### ISSUE TITLE
OpenDNS refuses DNS resolution to libuv.org

### ISSUE THREAD

**Issue by genio** [libuv/libuv.github.io#2]
Since using Umbrella in the office, we're unable to access the libuv.org web site. After investigating, it claims there's an overall issue:

![image](https://user-images.githubusercontent.com/109551/95510063-5a94d080-0983-11eb-987f-f29bafba4e82.png)

![image](https://user-images.githubusercontent.com/109551/95510096-65e7fc00-0983-11eb-9290-6efb54c76fc1.png)

Would you mind double-checking things to see if DNS for libuv.org is setup correctly, please?

**Comment by bnoordhuis** [comment]
I don't see anything obviously wrong with how libuv.org is currently configured.

It's a CNAME for `libuv.github.io.` (dot intentional, FQDN) and those IP addresses are indeed Github's addresses for github.io.

What may be confusing that tool you're using (although I don't see anything wrong with it) is that the SOA record for libuv.org points to `ns111.auroradns.eu. admin.auroradns.eu.` whereas the SOA record for github.io points to `ns-1622.awsdns-10.co.uk. awsdns-hostmaster.amazon.com.`.

**Comment by genio** [comment]
Right. There are several other GH sites that are setup nearly the same way as libuv.org. They get the same weird info on MXToolBox, but they resolve on OpenDNS. OpenDNS seems to have something against libuv.org. Is that something y'all can reach out to them on and work out?

**Comment by bnoordhuis** [comment]
I wouldn't know how. The support options on https://www.opendns.com/ assume you're a customer and I'm not about to create an account with them.

You're their customer, right? Can I suggest you get in touch with them? They're welcome to follow up in our issue tracker or get in touch with me over email.

I'll close this out but can reopen if necessary.

**Comment by bnoordhuis** [comment]
On second thought, I'll leave this open a little longer. I'd like to know if more people experience the same issue.

**Comment by vtjnash** [comment]
Seems stale now
